//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> subtipoactivo { get; set; }
        public Nullable<int> empleado { get; set; }
        public Nullable<int> oficina { get; set; }
        public Nullable<int> seguro { get; set; }
    
        public virtual empleado empleado1 { get; set; }
        public virtual oficina oficina1 { get; set; }
        public virtual seguro seguro1 { get; set; }
        public virtual subtipoactivo subtipoactivo1 { get; set; }
    }
}
