//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivoFijoEntities : DbContext
    {
        public ActivoFijoEntities()
            : base("name=ActivoFijoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catalogo> catalogo { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<movimiento> movimiento { get; set; }
        public virtual DbSet<oficina> oficina { get; set; }
        public virtual DbSet<proformacab> proformacab { get; set; }
        public virtual DbSet<proformadet> proformadet { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<seguro> seguro { get; set; }
        public virtual DbSet<subtipoactivo> subtipoactivo { get; set; }
        public virtual DbSet<tipoactivo> tipoactivo { get; set; }
        public virtual DbSet<tipomovimiento> tipomovimiento { get; set; }
    }
}
