//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        public int id { get; set; }
        public Nullable<int> tipomovimiento { get; set; }
        public Nullable<int> empleadoorigen { get; set; }
        public Nullable<int> empleadodestino { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> tiempoduracion { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual empleado empleado1 { get; set; }
        public virtual tipomovimiento tipomovimiento1 { get; set; }
    }
}
